# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS-Simple-Todos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS-Simple-Todos

  target 'IOS-Simple-TodosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOS-Simple-TodosUITests' do
    # Pods for testing
  end

end
